// for all data get from blogs
export const GET_DATA_BLOGS_REQUEST="GET_DATA_BLOGS_REQUEST";
export const GET_DATA_BLOGS_SUCCESS="GET_DATA_BLOGS_SUCCESS";
export const GET_DATA_BLOGS_FAILURE="GET_DATA_BLOGS_FAILURE";

// for all data add =>blog post 
export const ADD_DATA_BLOGS_REQUEST="ADD_DATA_BLOGS_REQUEST";
export const ADD_DATA_BLOGS_SUCCESS="ADD_DATA_BLOGS_SUCCESS";
export const ADD_DATA_BLOGS_FAILURE="ADD_DATA_BLOGS_FAILURE";

// for all update blogs
export const UPDATE_DATA_BLOGS_REQUEST="UPDATE_DATA_BLOGS_REQUEST";
export const UPDATE_DATA_BLOGS_SUCCESS="UPDATE_DATA_BLOGS_SUCCESS";
export const UPDATE_DATA_BLOGS_FAILURE="UPDATE_DATA_BLOGS_FAILURE";


// for all delete users data
export const DELETE_DATA_BLOGS_REQUEST="DELETE_DATA_BLOGS_REQUEST";
export const DELETE_DATA_BLOGS_SUCCESS="DELETE_DATA_BLOGS_SUCCESS";
export const DELETE_DATA_BLOGS_FAILURE="DELETE_DATA_BLOGS_FAILURE";